web.ribbon:
  ribbon:
    listOfServers : localhost:8002   #����ֻʹ��һ̨ribbon������

ribbon:
  eureka:
    enabled: false  #��ֹ��eureka����

spring:
  application:
    name: client.feigh

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
    healthcheck:
      enabled: true
logging:
  level:
    com.example.demo.feign.MyFeign1: DEBUG